### PR TITLE
🔖 Rc/1.5.0

### PR DESCRIPTION
**Pull request by anncatton**
#236 
#238 
#240 
#228 
#229 
#230 
#237 
#239 
#341 
#340 
#292

### CODE REVIEW

**Comment by caravinci** [comment]
Holy commits! lol
reviewing now

**Review by joneubank — APPROVED** [review]
👏

**Review by caravinci — APPROVED** [review]
🚀

**Comment by anncatton** [comment]
> Holy commits! lol reviewing now

a few months of work here 🙂

**Pull request merged**
